[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink=lib/chainlink-brownie-contracts/",
    "@solmate=lib/solmate/src/",
    '@openzeppelin=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src/',
    'foundry-devops/=lib/foundry-devops/src/',
]
ffi = true
fs_permissions = [{ access = "read", path = "./img/" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
